# https://qiita.com/gon0821/items/77369def082745d19c38
services:
  db: 
    image: postgres:17.0
    volumes: 
      - ./containers/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # $で.envの環境変数名を指定
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
  
  app: # Flask用
    build:
      context: ./containers/python/ # 基本的にDockerfileのディレクトリにするといいかも？
    depends_on: # 依存関係。dbが起動したあとにappが起動される
      - "db"
    working_dir: /code/python/ # 作業ディレクトリの指定
    volumes:
      - ./code/python/:/code/python/ # 中のディレクトリはDockerfileでRUN mkdirで新規作成する場所 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # $で.envの環境変数名を指定
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - FLASK_APP=${FLASK_APP} # モジュールを指定=__init__.pyが自動実行=main.pyが自動実行される
      - FLASK_DEBUG=${FLASK_DEBUG} # 1はTRUEなのでデバッグモードがON。本番環境ではデバッグモードOFFにする
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
    ports:
      - "${FLASK_RUN_PORT}:5000" # 他と衝突しなければなんでもいい

  django:
    build:
      context: ./containers/django/
    depends_on:
      - "db"
    working_dir: /code/django/circleproject/
    volumes:
      - ./code/django/:/code/django/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    ports:
      - "${DJANGO_PORT}:8000"
