# https://qiita.com/gon0821/items/77369def082745d19c38
services:
  db: # ここがコンテナ名になる
    image: postgres:17.0
    volumes: 
      - ./containers/postgresql/data/:/var/lib/postgresql/data/
    restart: always #コンテナが死んだとき自動再起動するかどうか
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # $で.envの環境変数名を指定
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
  
  app:
    build:
      context: ./containers/python/ # 基本的にDockerfileのディレクトリにするといいかも？
    working_dir: /code/python/ # 作業ディレクトリの指定
    volumes:
      - ./code/python/:/code/python/ # 中のディレクトリはDockerfileでRUN mkdirで新規作成する場所 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # $で.envの環境変数名を指定
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - FLASK_APP=${FLASK_APP} # モジュールを指定=__init__.pyが自動実行=main.pyが自動実行される
      - FLASK_DEBUG=${FLASK_DEBUG} # 1はTRUEなのでデバッグモードがON。本番環境ではデバッグモードOFFにする
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
    ports:
      - "${FLASK_RUN_PORT}:5000" # 他と衝突しなければなんでもいい
